draft: add gitlab support for repositories under 4-appfactory
GoogleCloudPlatform/terraform-google-enterprise-application pull request #290
Opened 2024-12-05 13:42 UTC by caetano-colin

2024-12-10 19:53 UTC, gtsorbo requested changes

2024-12-10 19:53 UTC, gtsorbo commented on 4-appfactory/modules/app-group-baseline/main.tf
> +  source = "git::https://github.com/terraform-google-modules/terraform-google-bootstrap.git//modules/cloudbuild_repo_connection?ref=a6072e0db92d976f1535dab767ad6b4331bcb4ef"
Can we update with registry release now? https://github.com/terraform-google-modules/terraform-google-bootstrap/releases/tag/v10.0.0

2024-12-10 20:13 UTC, apeabody commented on 4-appfactory/README.md
> +To proceed with github as your git provider you will need:
```suggestion
To proceed with GitHub as your git provider you will need:
```

2024-12-10 20:13 UTC, apeabody commented on 4-appfactory/README.md
> +To proceed with gitlab as your git provider you will need:
```suggestion
To proceed with Gitlab as your git provider you will need:
```

2024-12-19 21:04 UTC, apeabody commented on test/integration/appfactory/appfactory_test.go
> +					triggerRegion := "us-central1"
Thanks @caetano-colin! If we'd done that originally, wouldn't have had to change it now.

2024-12-19 23:23 UTC, merged