feat: added cymbal bank frontend integration test
GoogleCloudPlatform/terraform-google-enterprise-application pull request #53
Opened 2024-03-20 20:30 UTC by yliaog

2024-03-25 17:47 UTC, apeabody requested changes

2024-03-25 17:47 UTC, apeabody commented on test/integration/appsource/cymbal-bank/frontend/frontend_test.go
> +// Copyright 2024 Google LLC
I think this file should just go in `test/integration/appsource/` for the cft auto discovery?

2024-04-11 18:12 UTC, yliaog commented
/close

2024-04-11 18:13 UTC, yliaog commented
this pr has been incorporated into the other pr.

2024-04-11 18:13 UTC, closed without merging