feat: adjusted sqli cloudarmor rule sensitivity level 1 to allow for cymbal bank app
GoogleCloudPlatform/terraform-google-enterprise-application pull request #85
Opened 2024-04-25 00:44 UTC by yliaog

…k app cookies

2024-04-25 15:49 UTC, apeabody commented
flake failure, retriggering

2024-04-25 19:26 UTC, apeabody requested changes
Hi @yliaog - I did some testing, and I think we might be able to retain sqli-v33 if we drop the sensitivity to level 1.

2024-04-25 23:12 UTC, apeabody approved these changes

2024-04-25 23:13 UTC, apeabody commented on 2-multitenant/modules/env_baseline/main.tf
>      "sqli_sensitivity_level_4" = {
nit

```suggestion
    "sqli_sensitivity_level_1" = {
```

2024-04-25 23:31 UTC, yliaog commented on 2-multitenant/modules/env_baseline/main.tf
>      "sqli_sensitivity_level_4" = {
fixed.

2024-04-26 01:38 UTC, yliaog commented
/gcbrun

2024-04-26 16:38 UTC, gtsorbo approved these changes

2024-04-26 16:42 UTC, merged